name: Karen Bito
favicon: null
layout_spectrum: 0.97218
typography_spectrum: 0.46328402985818684
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#332e3e'
    - '#e0dbd8'
    - '#244fc9'
    - '#ad8d99'
    - '#fefdfe'
  brandStrength: 0.5
  lightness: 0.08075162209570408
  saturation: 1
  rhythmicContrast: 0.33802660880610347
purpose: []
