name: Karen Bito
favicon: null
layout_spectrum: 1
typography_spectrum: 0.40263
title: Simply Candid Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75993505-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#7c8db4'
    - '#ac0003'
    - '#603c22'
    - '#fb7c7a'
  brandStrength: 0.25
  lightness: 0.08075162209570408
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
