name: Karen Bito
favicon: null
layout_spectrum: 0.97218
typography_spectrum: 0.46328402985818684
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#220021'
    - '#d0cfca'
    - '#5d3a3f'
    - '#9e002c'
    - '#ea7548'
  brandStrength: 0.9375
  lightness: 0.08075162209570408
  saturation: 1
  rhythmicContrast: 0.33802660880610347
purpose: []
